---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: clubhive-https-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/api`)
      priority: 20
      services:
        - name: server-service
          port: 3000
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`)
      priority: 10
      services:
        - name: client-service
          port: 80
  tls:
    secretName: clubhive-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: clubhive-https-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: clubhive-http-ingress
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`) && !PathPrefix(`/.well-known/acme-challenge/`)
      middlewares:
        - name: clubhive-https-redirect
      services:
        - name: client-service
          port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: clubhive-tls
spec:
  secretName: clubhive-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}
