{{- $mongoSecret := lookup "v1" "Secret" .Release.Namespace "mongodb-secret" }}
{{- $mongoPassword := "" }}
{{- if $mongoSecret }}
  {{- $mongoPassword = index $mongoSecret.data "password" }}
{{- else }}
  {{- $mongoPassword = randAlphaNum 32 | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ "admin" | b64enc | quote }}
  password: {{ $mongoPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: env-vars
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:{{ $mongoPassword | b64dec }}@mongodb-service:27017/clubhive?authSource=admin"
