{{- $mongoPassword := randAlphaNum 32 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ "admin" | b64enc | quote }}
  password: {{ $mongoPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: env-vars
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:{{ $mongoPassword }}@mongodb-service:27017/clubhive?authSource=admin"
